language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
# command to install dependencies
install:
        - pip install -U pytest 
script: python -m pytest test_*

branches:
    only:
        - master
